### ISSUE TITLE
Feature Request: Request AppTrackingTransparency for iOS 14+

### ISSUE THREAD

**Issue by nickgoh** [bdlukaa/native_admob_flutter#3]
Function to request app tracking transparency in iOS 14+.

https://support.google.com/admob/answer/9997589?hl=en

**Comment by bdlukaa** [comment]
Since iOS is not supported yet, this function is not avaiable. iOS support is planned for the plugin version 1.0.0, the function and its documentation will be avaiable at that version.

Useful links: 
  - https://developers.google.com/admob/ios/ios14#request
  - https://github.com/bdlukaa/native_admob_flutter/tree/dev

**Comment by bdlukaa** [comment]
Fixed in [1.0.0](https://pub.dev/packages/native_admob_flutter)
