### ISSUE TITLE
When calling mobileads.initialize app app turns blank like a blink 

### ISSUE THREAD

**Issue by sushilbalami** [bdlukaa/native_admob_flutter#7]
App turns blank like a blink for sometime....

**Comment by sushilbalami** [comment]
![Uploading BCA-Nepal.GIF…]()

**Comment by bdlukaa** [comment]
That's probably because you didn't set a splashscreen on the platform side.
Useful links:
  - https://pub.dev/packages/flutter_native_splash (Android, iOS and Web)
 
If it continues to happen with a splashscreen, please comment here with more details.
If it solves your problem, tell me, so I can close the issue

**Comment by sushilbalami** [comment]
nono when i remove that initialize nothing happens,,,
after putting initialize this issue came..
it didnt cause problem but seems some flikkery..

**Comment by bdlukaa** [comment]
I could reproduce your issue, and the flickery was gone after I added a proper splashscreen.
- https://flutter.dev/docs/development/ui/advanced/splash-screen#android-launch-screen

**Comment by sushilbalami** [comment]
umm solved but conflicted with firebase messaging maybe it is the problem of another package now.. 
thanks,.
